# 如果要用加密函数E() 如:E(123456)
# 如果要用解密函数D() 如:D(4x8VBfSLlFy3jvd8R3q5RQ==)
Subscribe: # 订阅配置
  Sub_DN: 'D(oE2xmBd+2l+ABwkMGV61vg==)'
  Sub_Vless_Prot: 4333
  Sub_Vmess_Prot: 4334
  Sub_Socks_Prot: 4335
  Sub_UUID: "D(AZJEbYAK8PDs0f4NcjUZShxAgeNnK1xyA1X2OuLNTQxz8a5N90NCk8HlGd/5bJVQ)"
  Sub_Socks_PWD: "D(6+7GQBYQ0Hp0usYMwI52L9AL+fH3yCWkvYXSOCSkWuo=)"

DDNS: # 解析配置
  AccessKeyID: 'D(XXXXXXXX)'
  AccessKey: 'D(XXXXXXXXXXXXXX)'
  #如: example.com
  DomainName: 'example.com'
  #如: www ,@
  RR: 'www'
  
Wake-on-LAN: # 网络唤醒配置
  #局域网广播地址
  IP: 10.10.10.255
  #唤醒MAC地址
  电脑: 'XX:XX:XX:XX:XX:XX'
  NAS: 'XX:XX:XX:XX:XX:XX'
  
Port: # 端口配置
  #如 OPENWRT: 80
  OP: 8
  OPENWRT: 8
  ASUS: 6
  软路由: 8
  路由器: 6
  FN: 5666
  飞牛: 5666
  OPENLIST: 5244
  本地网盘: 5244
Message: 
  订阅: E(BStTGzVhblofmEXoUO/cbAFfZVZJ1kBoWqrk3wp8smxPiWZsQoyJC4Hn0MCbTYub)
  IP订阅: E(BStTGzVhblofmEXoUO/cbAFfZVZJ1kBoWqrk3wp8smwX9J9/+59+/PniRGeRnv2e)
  DN订阅: E(BStTGzVhblofmEXoUO/cbAFfZVZJ1kBoWqrk3wp8smzyTs6oN1eCfaB3Rz/7yDc2)
  
  
  
  